### ISSUE TITLE
Is HTTPS-only for linking to majola necessary?

### ISSUE THREAD

**Issue by chrisafraser** [Atelier-Shiori/OngakuKiroku#1]
Not sure if this is a design decision or not, but I was trying to test out maloja + OngakuKiroku to see how they work compared to last.fm. I was unable to open the scrobble log and am not seeing any traffic to maloja on my machine, so I assume its that I am not using HTTPS. Setting up a reverse proxy + valid tls certificates for testing purposes is non-trivial just for testing purposes.

Otherwise this tool looks *awesome*.

**Comment by moyitpro** [comment]
Actually, App Transport Security, which requires HTTPS is turned off in the app, so it can work with HTTP (non-secure).

The Scrobbler Log not viewing bug is fixed in Alpha 2.

https://github.com/Atelier-Shiori/OngakuKiroku/releases/tag/1.0-alpha2

**Comment by chrisafraser** [comment]
Thanks, alpha 2 is working great now!  My problem was an invalid API key.
